sudo: required
services:
  - docker

before_install:
  - docker build -t tashigurung/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tashigurung/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t tashigurung/multi-client ./client
  - docker build -t tashigurung/multi-nginx ./nginx
  - docker build -t tashigurung/multi-server ./server
  - docker build -t tashigurung/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push to Docker Hub
  - docker push tashigurung/multi-client
  - docker push tashigurung/multi-nginx
  - docker push tashigurung/multi-server
  - docker push tashigurung/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-010003941817"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY